<?php 
	$title="index";
	include 'include/header.php';?>

<script type="text/javascript">
			$(function(){

				// Accordion
				$("#accordion").accordion({ header: "h3" });
	
				// Tabs
				$('#tabs').tabs();
	

				// Dialog			
				$('#dialog').dialog({
					autoOpen: false,
					width: 600,
					buttons: {
						"Ok": function() { 
							$(this).dialog("close"); 
						}, 
						"Cancel": function() { 
							$(this).dialog("close"); 
						} 
					}
				});
				
				// Dialog Link
				$('#dialog_link').click(function(){
					$('#dialog').dialog('open');
					return false;
				});

				// Datepicker
				$('#datepicker').datepicker({
					inline: true
				});
				
				// Slider
				$('#slider').slider({
					range: true,
					values: [17, 67]
				});
				
				// Progressbar
				$("#progressbar").progressbar({
					value: 20 
				});
				
				//hover states on the static widgets
				$('#dialog_link, ul#icons li').hover(
					function() { $(this).addClass('ui-state-hover'); }, 
					function() { $(this).removeClass('ui-state-hover'); }
				);
				
			});
		</script>

<h1>Welcome to Group 19's database application in Advanced Databases (INFC20).</h1>
<p>&nbsp;</p>
<div id="accordion">
	<div>
		<h3><a href="#">Introduction</a></h3>
		<div>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor
		sit amet.</div>
	</div>
	<div>
		<h3><a href="#">FAQ</a></h3>
		<div>Phasellus mattis tincidunt nibh.</div>
	</div>
	<div>
		<h3><a href="#">The people</a></h3>
		<div>Nam dui erat, auctor a, dignissim quis.</div>
	</div>
</div>

<!-- Tabs -->
<h2>Tabs</h2>
<div id="tabs">
<ul>
	<li><a href="#tabs-1">First</a></li>
	<li><a href="#tabs-2">Second</a></li>
	<li><a href="#tabs-3">Third</a></li>
</ul>
<div id="tabs-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.</div>
<div id="tabs-2">Phasellus mattis tincidunt nibh. Cras orci urna, blandit id,
pretium vel, aliquet ornare, felis. Maecenas scelerisque sem non nisl. Fusce sed
lorem in enim dictum bibendum.</div>
<div id="tabs-3">Nam dui erat, auctor a, dignissim quis, sollicitudin eu, felis.
Pellentesque nisi urna, interdum eget, sagittis et, consequat vestibulum, lacus.
Mauris porttitor ullamcorper augue.</div>
</div>

<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
<h2 class="demoHeaders">Dialog</h2>
<p><a
	href="#"
	id="dialog_link"
	class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>Open
Dialog</a></p>

<!-- ui-dialog -->
<div
	id="dialog"
	title="Dialog Title">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.</p>
</div>

<?php include 'include/footer.php';?>


