DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS section;
DROP TABLE IF EXISTS course_requirements;
DROP TABLE IF EXISTS studies;
DROP TABLE IF EXISTS has_studied;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;